### ISSUE TITLE
Fix Open Horizon navbar Search

### ISSUE THREAD

**Issue by johnwalicki** [open-horizon/open-horizon.github.io#383]
The #382 PR has an invalid `"` html which causes the Search box to not render on Firefox (Linux and Mac).  It looks fine on Chrome.  This issue fixes the 
```
_includes/open-horizon-navbar-logo.html
```

**Comment by johnwalicki** [comment]
See https://github.com/open-horizon/open-horizon.github.io/issues/381#issuecomment-1407473284

**Comment by dipesh-rawat** [comment]
@johnwalicki Just noticed this. Apologies for introducing an intended bug. 
I see you have raised a PR with removing the `"` but unfortunately the issue still remains after that. I have resolved the bug in a separate branch by using standard `<div>` tag instead of using `<picture>` tag with some css changes. I have attached the screenshot below.
Do let me know if you want me to raise a PR with fix or you are planning to copy them into the existing PR #384

<img width="1501" alt="browser-fix" src="https://user-images.githubusercontent.com/13051389/215291156-3121b98c-e4a7-42fb-935c-890c2d772b15.png">
